"""
Theme properties
"""
import dataclasses as dt


@dt.dataclass(eq=False, frozen=True)
class IconName:
    AddComment = "icons/add-comment.svg"
    AdminPanelSettings = "icons/admin-panel-settings.svg"
    Album = "icons/album.svg"
    MainApp = "icons/app.png"
    App = "icons/app.svg"
    ArrowDown = "icons/arrow-down.svg"
    ArrowRight = "icons/arrow-right.svg"
    ArrowUp = "icons/arrow-up.svg"
    AutoDelete = "icons/auto-delete.svg"
    Backup = "icons/backup.svg"
    Bolt = "icons/bolt.svg"
    BookmarkAdded = "icons/bookmark-added.svg"
    BookmarkManager = "icons/bookmark-manager.svg"
    BookmarkRemove = "icons/bookmark-remove.svg"
    Bookmark = "icons/bookmark.svg"
    Bookmarks = "icons/bookmarks.svg"
    Box = "icons/box.svg"
    Close = "icons/close.svg"
    ClosedCaption = "icons/closed-caption.svg"
    CloudUpload = "icons/cloud-upload.svg"
    Cloud = "icons/cloud.svg"
    CropFree = "icons/crop-free.svg"
    CropRotate = "icons/crop-rotate.svg"
    Crop = "icons/crop.svg"
    Delete = "icons/delete.svg"
    DiscoverTune = "icons/discover-tune.svg"
    Download = "icons/download.svg"
    Edit = "icons/edit.svg"
    Error = "icons/error.svg"
    FastForward = "icons/fast-forward.svg"
    FastRewind = "icons/fast-rewind.svg"
    FolderCopy = "icons/folder-copy.svg"
    FolderData = "icons/folder-data.svg"
    FolderDelete = "icons/folder-delete.svg"
    FolderManaged = "icons/folder-managed.svg"
    FolderOpen = "icons/folder-open.svg"
    FolderSpecial = "icons/folder-special.svg"
    FolderZip = "icons/folder-zip.svg"
    Folder = "icons/folder.svg"
    Hourglass = "icons/hourglass.svg"
    Info = "icons/info.svg"
    Keyboard = "icons/keyboard.svg"
    Logout = "icons/logout.svg"
    Mood = "icons/mood.svg"
    MusicNote = "icons/music-note.svg"
    Package = "icons/package.svg"
    Palette = "icons/palette.svg"
    Pause = "icons/pause.svg"
    PlayArrow = "icons/play-arrow.svg"
    PlayPause = "icons/play-pause.svg"
    PlaylistAdd = "icons/playlist-add.svg"
    PlaylistPlay = "icons/playlist-play.svg"
    PowerSettingsNew = "icons/power-settings-new.svg"
    Preferences = "icons/preferences.svg"
    QueueMusic = "icons/queue-music.svg"
    RateReview = "icons/rate-review.svg"
    Redo = "icons/redo.svg"
    Refresh = "icons/refresh.svg"
    Reload = "icons/reload.svg"
    Repeat = "icons/repeat.svg"
    Replay = "icons/replay.svg"
    Restore = "icons/restore.svg"
    Save = "icons/save.svg"
    Search = "icons/search.svg"
    SentimentStressed = "icons/sentiment-stressed.svg"
    SettingsInputComponent = "icons/settings-input-component.svg"
    SettingsPower = "icons/settings-power.svg"
    SettingsVoice = "icons/settings-voice.svg"
    Subtitles = "icons/subtitles.svg"
    Sync = "icons/sync.svg"
    ToggleOff = "icons/toggle-off.svg"
    ToggleOn = "icons/toggle-on.svg"
    Tune = "icons/tune.svg"
    Undo = "icons/undo.svg"
    VideoStable = "icons/video-stable.svg"
    VolumeDown = "icons/volume-down.svg"
    VolumeMute = "icons/volume-mute.svg"
    VolumeOff = "icons/volume-off.svg"
    VolumeUp = "icons/volume-up.svg"
    Warning = "icons/warning.svg"
    WbIncandescent = "icons/wb-incandescent.svg"


@dt.dataclass(eq=False, frozen=True)
class ThemeProperties:
    AppIconColor: str = "appIconColor"
    ActionIconColor: str = "actionIconColor"
    ErrorColor: str = "errorColor"
    DangerColor: str = "dangerColor"
    MainFontColor: str = "mainFontColor"
